# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sql_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(843, 522)
        Form.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("font: 14pt \"Arial\";")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.sqlacodegen_path_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.sqlacodegen_path_lineEdit.setReadOnly(True)
        self.sqlacodegen_path_lineEdit.setObjectName("sqlacodegen_path_lineEdit")
        self.horizontalLayout_7.addWidget(self.sqlacodegen_path_lineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.generate_file_path_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.generate_file_path_lineEdit.setReadOnly(True)
        self.generate_file_path_lineEdit.setObjectName("generate_file_path_lineEdit")
        self.horizontalLayout_2.addWidget(self.generate_file_path_lineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setStyleSheet("font: 14pt \"Arial\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.db_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.db_port_lineEdit.setObjectName("db_port_lineEdit")
        self.horizontalLayout_3.addWidget(self.db_port_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.db_username_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.db_username_lineEdit.setObjectName("db_username_lineEdit")
        self.horizontalLayout_4.addWidget(self.db_username_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.db_pwd_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.db_pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.db_pwd_lineEdit.setObjectName("db_pwd_lineEdit")
        self.horizontalLayout_5.addWidget(self.db_pwd_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.db_conn_test_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.db_conn_test_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.db_conn_test_pushButton.setObjectName("db_conn_test_pushButton")
        self.horizontalLayout_6.addWidget(self.db_conn_test_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.db_host_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.db_host_lineEdit.setObjectName("db_host_lineEdit")
        self.horizontalLayout.addWidget(self.db_host_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.db_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.db_name_lineEdit.setObjectName("db_name_lineEdit")
        self.horizontalLayout_13.addWidget(self.db_name_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_13, 4, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setStyleSheet("font: 14pt \"Arial\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.export_mode_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.export_mode_comboBox.setObjectName("export_mode_comboBox")
        self.export_mode_comboBox.addItem("")
        self.export_mode_comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.export_mode_comboBox)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 10)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.generate_file_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.generate_file_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.generate_file_pushButton.setObjectName("generate_file_pushButton")
        self.horizontalLayout_11.addWidget(self.generate_file_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(81, 0))
        self.label_7.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.export_filename_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.export_filename_lineEdit.setObjectName("export_filename_lineEdit")
        self.horizontalLayout_8.addWidget(self.export_filename_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.db_table_label = QtWidgets.QLabel(self.groupBox_3)
        self.db_table_label.setMinimumSize(QtCore.QSize(81, 0))
        self.db_table_label.setMaximumSize(QtCore.QSize(81, 16777215))
        self.db_table_label.setObjectName("db_table_label")
        self.horizontalLayout_10.addWidget(self.db_table_label)
        self.db_table_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.db_table_comboBox.setObjectName("db_table_comboBox")
        self.horizontalLayout_10.addWidget(self.db_table_comboBox)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 10)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setStyleSheet("font: 13pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "sqlacodegen"))
        self.label_6.setText(_translate("Form", "工具路径:"))
        self.label_2.setText(_translate("Form", "文件路径:"))
        self.groupBox_2.setTitle(_translate("Form", "数据库"))
        self.label_3.setText(_translate("Form", "端口:"))
        self.db_port_lineEdit.setText(_translate("Form", "3306"))
        self.label_4.setText(_translate("Form", "用户:"))
        self.db_username_lineEdit.setText(_translate("Form", "root"))
        self.label_5.setText(_translate("Form", "密码:"))
        self.db_pwd_lineEdit.setText(_translate("Form", "19940124"))
        self.db_conn_test_pushButton.setText(_translate("Form", "连接测试"))
        self.label.setText(_translate("Form", "主机:"))
        self.db_host_lineEdit.setText(_translate("Form", "127.0.0.1"))
        self.label_9.setText(_translate("Form", "库名:"))
        self.db_name_lineEdit.setText(_translate("Form", "blogin"))
        self.groupBox_3.setTitle(_translate("Form", "导出设置"))
        self.label_8.setText(_translate("Form", "导出模式:"))
        self.export_mode_comboBox.setItemText(0, _translate("Form", "数据库"))
        self.export_mode_comboBox.setItemText(1, _translate("Form", "单表"))
        self.generate_file_pushButton.setText(_translate("Form", "生成model"))
        self.label_7.setText(_translate("Form", "文件名:"))
        self.db_table_label.setText(_translate("Form", "选择表:"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))

